### ISSUE TITLE
Uncatched error when no parameters are given

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/AIVPN#35]
**Describe the bug**
when no parameters are given, an error is shown that is not catched

**To Reproduce**
1. python3 aivpn.py --redis "x.x.x.x" audit
Traceback (most recent call last):
  File "aivpn.py", line 314, in <module>
    cli_action(redis_client,params)
NameError: name 'cli_action' is not defined

**Expected behavior**
Not to give an error but give help

**Desktop (please complete the following information):**
 - OS: Linux Debian
 - Version CPU amd6. Debian unstable

**Comment by ay-bh** [comment]
@eldraco @verovaleros I would love to work on this.

**Comment by eldraco** [comment]
Hi @ay-bh, yes I think is a good one! let us know how it goes
